pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@github.com:salaesp/mecanik.git
          - cd mecanik.git
          - git push -f --mirror git@github.com:salaesp/mecanik.git