pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        script:
          - git clone --mirror git@github.com:salaesp/mecanik.git ./mirrored
          - cd ./mirrored;
          - git fetch -p --tags origin;
          - git push --mirror git@github.com:salaesp/mecanik.git