pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --mirror git@github.com:salaesp/mecanik.git ./mirrored
          - cd ./mirrored;
          - git fetch -p --tags origin;
          - git push --mirror git@github.com:salaesp/mecanik.git