spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:file:./db/autitos
    name: autitos
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  session:
    store-type: redis